FROM node:20-alpine AS base

WORKDIR /app

COPY package*.json ./
COPY packages/shared/package*.json ./packages/shared/
COPY apps/web/package*.json ./apps/web/

RUN npm ci

COPY packages/shared ./packages/shared
COPY apps/web ./apps/web

RUN npm run build --workspace=@muza/shared
RUN npm run build --workspace=@muza/web

EXPOSE 3000

CMD ["npm", "run", "start:web"]
