export enum UserRole {
  OWNER = 'OWNER',
  ADMIN = 'ADMIN',
  EDITOR = 'EDITOR',
  VIEWER = 'VIEWER',
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
}

export enum VideoStatus {
  DISCOVERED = 'DISCOVERED',
  DOWNLOADING = 'DOWNLOADING',
  DOWNLOADED = 'DOWNLOADED',
  PROCESSING = 'PROCESSING',
  ANALYZING = 'ANALYZING',
  GENERATING_CONTENT = 'GENERATING_CONTENT',
  READY_FOR_REVIEW = 'READY_FOR_REVIEW',
  APPROVED = 'APPROVED',
  SCHEDULED = 'SCHEDULED',
  PUBLISHING = 'PUBLISHING',
  PUBLISHED = 'PUBLISHED',
  PARTIALLY_PUBLISHED = 'PARTIALLY_PUBLISHED',
  FAILED = 'FAILED',
  ARCHIVED = 'ARCHIVED',
}

export enum SocialPlatform {
  YOUTUBE = 'YOUTUBE',
  INSTAGRAM = 'INSTAGRAM',
}

export enum PublishJobStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}

export enum YouTubePrivacy {
  PRIVATE = 'PRIVATE',
  UNLISTED = 'UNLISTED',
  PUBLIC = 'PUBLIC',
}

export enum AuditAction {
  USER_REGISTERED = 'USER_REGISTERED',
  USER_LOGGED_IN = 'USER_LOGGED_IN',
  USER_LOGGED_OUT = 'USER_LOGGED_OUT',
  DRIVE_CONNECTED = 'DRIVE_CONNECTED',
  DRIVE_DISCONNECTED = 'DRIVE_DISCONNECTED',
  DRIVE_FOLDER_SYNCED = 'DRIVE_FOLDER_SYNCED',
  VIDEO_DISCOVERED = 'VIDEO_DISCOVERED',
  VIDEO_IMPORTED = 'VIDEO_IMPORTED',
  VIDEO_PROCESSED = 'VIDEO_PROCESSED',
  AI_ANALYSIS_COMPLETED = 'AI_ANALYSIS_COMPLETED',
  AI_CONTENT_GENERATED = 'AI_CONTENT_GENERATED',
  CONTENT_EDITED = 'CONTENT_EDITED',
  CONTENT_APPROVED = 'CONTENT_APPROVED',
  CONTENT_REJECTED = 'CONTENT_REJECTED',
  PUBLISH_SCHEDULED = 'PUBLISH_SCHEDULED',
  VIDEO_PUBLISHING_STARTED = 'VIDEO_PUBLISHING_STARTED',
  VIDEO_PUBLISHED = 'VIDEO_PUBLISHED',
  PUBLISH_FAILED = 'PUBLISH_FAILED',
  SETTINGS_UPDATED = 'SETTINGS_UPDATED',
  SOCIAL_ACCOUNT_CONNECTED = 'SOCIAL_ACCOUNT_CONNECTED',
  SOCIAL_ACCOUNT_DISCONNECTED = 'SOCIAL_ACCOUNT_DISCONNECTED',
}
